app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('polls/', include('polls.urls')),

    path('admin/', admin.site.urls),
]

app/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

app/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='details'),
    path('<int:pk>/result/', views.ResultView.as_view(), name='result'),
    path('<int:pk>/vote/', views.vote, name='vote'),
]

app/main/models.py
from django.db import models

app/polls/models.py
import datetime

from django.contrib import admin
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_data = models.DateTimeField('data published')

    def __str__(self):
        return "{}: {}".format(self.id, self.question_text)

    @admin.display(
        boolean=True,
        ordering='pub_data',
        description='Published recently?'
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_data <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return "{}: {}".format(self.id, self.choice_text)

app/main/views.py
from django.db.models import F
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse


def index(request):
    return HttpResponseRedirect(reverse('polls:index'))

app/polls/views.py
from django.db.models import F
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects \
            .filter(pub_data__lte=timezone.now()) \
            .order_by('-pub_data')[:5]


class DetailView(generic.DetailView):
    template_name = 'polls/details.html'
    model = Question

    def get_queryset(self):
        return Question.objects \
            .filter(pub_data__lte=timezone.now())



class ResultView(generic.DetailView):
    template_name = 'polls/result.html'
    model = Question


def vote(request, pk):
    question = get_object_or_404(Question, pk=pk)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/details.html', {
            'question': question,
            'error_message': "You didn't select a choice",
        })
    else:
        selected_choice.votes = F('votes') + 1
        selected_choice.save()
        selected_choice.refresh_from_db()

        redirect_path = reverse('polls:result', args=(question.id,))
        return HttpResponseRedirect(redirect_path)


# # ----------------
# #  Old responders
# # ----------------
# def polls(request):
#     latest_question_list = Question.objects.order_by('-pub_data')[:5]
#
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#
#     return render(request, 'polls/index.html', context)
#
#
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/details.html', {'question': question})
#
#
# def result(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/result.html', {'question': question})
#     # return HttpResponse("You're looking at the result of a question {}".format(question_id))

app/main/templates/polls/details.html
<form action="{% url 'main:vote' question.id %}" method="post">
    {% csrf_token %}

    <fieldset>
        <legend> <h1>{{ question.question_text }}</h1> </legend>
        {% if error_message %}
            <p> <strong> {{ error_mesaage }} </strong> </p>
        {% endif %}

        {% for choice in question.choice_set.all %}
            {% with cur_index=forloop.counter %}

                <input type="radio"
                       name="choice"
                       id="choice{{ cur_index }}"
                       value="{{ choice.id }}">
                <label for="choice{{ cur_index }}">
                    {{ choice.choice_text }}
                </label>
            {% endwith %}
        {% endfor %}

    </fieldset>

    <input type="submit" value="Vote">
</form>

{#{% if question.choice_set.count == 0 %}#}
{#    <p> No Choices </p>#}
{#{% else %}#}
{#    <ul>#}
{#        {% for choice in question.choice_set.all %}#}
{#            <li> {{ choice.choice_text }} </li>#}
{#        {% endfor %}#}
{#    </ul>#}
{#{% endif %}#}

app/main/templates/polls/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li>
                <a href="{% url 'main:details' question.id %}">{{ question.question_text }}</a>
{#                <a href="/polls/{{ question.id }}/">{{ question.question_text }}</a>#}
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p> No polls are available </p>
{% endif %}

app/main/templates/polls/result.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li> {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }} </li>
    {% endfor %}
</ul>

<a href="{% url 'main:details' question.id %}"> Vote again? </a>

app/polls/templates/polls/details.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}

    <fieldset>
        <legend> <h1>{{ question.question_text }}</h1> </legend>
        {% if error_message %}
            <p> <strong> {{ error_mesaage }} </strong> </p>
        {% endif %}

        {% for choice in question.choice_set.all %}
            {% with cur_index=forloop.counter %}

                <input type="radio"
                       name="choice"
                       id="choice{{ cur_index }}"
                       value="{{ choice.id }}">
                <label for="choice{{ cur_index }}">
                    {{ choice.choice_text }}
                </label>
            {% endwith %}
        {% endfor %}

    </fieldset>

    <input type="submit" value="Vote">
</form>

app/polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/main.css' %}">


{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li>
                <b> <h1>
                    <a href="{% url 'polls:details' question.id %}">{{ question.question_text }}</a>
{#                    <a href="/polls/{{ question.id }}/">{{ question.question_text }}</a>#}
                </h1> </b>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p> No polls are available </p>
{% endif %}

app/polls/templates/polls/result.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li> {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }} </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:details' question.id %}"> Vote again? </a>